#:schema ./config.schema.json

project_id = "project_id"

[api]
enabled = false
port = 54321

[auth]
[auth.email]
smtp.host = "inbucket"
smtp.admin_email = "admin@email.com"

[analytics]
port = 54326
